CREATE TABLE IF NOT EXISTS librepages_users (
	name VARCHAR(100) NOT NULL UNIQUE,
	email VARCHAR(100) UNIQUE NOT NULL,
	email_verified BOOLEAN DEFAULT NULL,
	password TEXT NOT NULL,
	ID SERIAL PRIMARY KEY NOT NULL
);
